Add optons -h/--help and --no-prompt pardump/parinit adhoc test run script

diff --git a/test/adhoc/pardump-parinit/run b/test/adhoc/pardump-parinit/run
--- a/test/adhoc/pardump-parinit/run
+++ b/test/adhoc/pardump-parinit/run
@@ -1,5 +1,30 @@
 #!/usr/bin/env bash
 
+show_help=false
+no_prompts=false
+
+while [ -n "$1" ]; do # while loop starts
+    case "$1" in
+    -h) show_help=true && shift ;;
+    --help) show_help=true && shift ;;
+    --no-prompts) no_prompts=true && shift ;;
+    *) echo "Option $1 not recognized" && exit 1 ;;
+    esac
+done
+
+if [ "$show_help" = true ] ; then
+    echo ""
+    echo "Options:"
+    echo "   -h/--help     - show this help message"
+    echo "   --no-prompts  - Don't prompt to continue after each run"
+    echo ""
+    echo "Usage:"
+    echo "   $0"
+    echo "   $0 --no-prompts"
+    echo ""
+    exit 0
+fi
+
 DIR=`dirname $0`
 DIR=`python -c "import os;print(os.path.abspath('$DIR'))"`
 echo "Script dir: $DIR"
@@ -9,13 +34,14 @@ echo "Repo dir: $REPO_DIR"
 
 
 prompt_to_continue () {
-    read -p "Do you want to continue? [yN]: " -r
-    echo
-    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-        echo "*** ABORTING."
-        exit 1
+    if [ "$no_prompts" = false ] ; then
+        read -p "Do you want to continue? [yN]: " -r
+        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+            echo "*** ABORTING."
+            exit 1
+        fi
+        echo "Continuing...."
     fi
-    echo "Continuing...."
 }
 
 check_return_code () {
